lib/catex_web/router.ex
defmodule CatexWeb.Router do
  @moduledoc false

  use CatexWeb, :router

  import CatexWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {CatexWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Catex.Authenticator
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through [:browser]

      live_dashboard "/dashboard",
        metrics: CatexWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

#  scope "/", CatexWeb do
#    pipe_through [:browser, :redirect_if_user_is_authenticated]
#
#    get "/users/register", UserRegistrationController, :new
#    post "/users/register", UserRegistrationController, :create
#    get "/users/log_in", UserSessionController, :new
#    post "/users/log_in", UserSessionController, :create
#    get "/users/reset_password", UserResetPasswordController, :new
#    post "/users/reset_password", UserResetPasswordController, :create
#    get "/users/reset_password/:token", UserResetPasswordController, :edit
#    put "/users/reset_password/:token", UserResetPasswordController, :update
#  end

  scope "/", CatexWeb do
    pipe_through [:browser, :require_authenticated_user]

    live "/hugs", HugLive.Index, :index
    live "/hugs/new", HugLive.Index, :new
    live "/hugs/:id/edit", HugLive.Index, :edit

    live "/hugs/:id", HugLive.Show, :show
    live "/hugs/:id/show/edit", HugLive.Show, :edit
  end

  scope "/admin", CatexWeb.Admin, as: :admin do
    pipe_through [:browser, :require_authenticated_user, :require_admin_user]

    resources "/users", UserController
    resources "/hugs", HugController
  end

  scope "/", CatexWeb do
    pipe_through [:browser]

    get "/", PageController, :index

    # Below 2 routers under redirect?
    get "/auth/login", AuthController, :login
    get "/auth/callback", AuthController, :callback

#    delete "/users/log_out", UserSessionController, :delete
    get "/auth/logout", AuthController, :logout
  end

  # Other scopes may use custom stacks.
  scope "/api", CatexWeb do
    pipe_through :api

    get "/hugs", HugController, :index
  end
end

lib/catex_web/live/hug_live/form_component.ex
defmodule CatexWeb.HugLive.FormComponent do
  @moduledoc false

  use CatexWeb, :live_component

  alias Catex.Hugs
  alias Catex.Hugs.HugParticipant
  alias Catex.Users

  @impl true
  def update(%{hug: hug} = assigns, socket) do
    changeset = Hugs.change_hug(hug)
    {
      :ok,
      socket
      |> assign(assigns)
      |> assign(:changeset, changeset)
      |> assign(
           :users,
           Users.list_users()
           |> Enum.filter(&(&1.id != assigns.current_user.id))
           |> Enum.map(&{&1.name, &1.id})
         )
      |> assign(
           :status_opts,
           #           [
           #             {"Consent pending", "consent_pending"},
           #             {"Consent given", "consent_given"},
           #             {"Consent denied", "consent_denied"},
           #             {"Hug pending", "hug_pending"},
           #             {"Hug confirmed", "hug_confirmed"},
           #             {"Hug denied", "hug_denied"}
           #           ],
           Hugs.status_flow()
         )
    }
  end

  @impl true
  def handle_event("add_participant", _params, socket) do
    participants =
      socket.assigns.changeset
      |> Ecto.Changeset.get_field(:participants, [])
        # The temp_id makes sure it does not overwrite the rest
      |> Enum.concat([%HugParticipant{temp_id: get_temp_id(), status: :consent_pending}])

    changeset = Ecto.Changeset.put_assoc(socket.assigns.changeset, :participants, participants)

    {
      :noreply,
      socket
      |> assign(changeset: changeset)
    }
  end

  # JUST TO GENERATE A RANDOM STRING
  defp get_temp_id,
       do:
         :crypto.strong_rand_bytes(5)
         |> Base.url_encode64()
         |> binary_part(0, 5)

  @impl true
  def handle_event("validate", %{"hug" => hug_params} = assigns, socket) do
    changeset =
      socket.assigns.hug
      |> Hugs.change_hug(hug_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"hug" => hug_params}, socket) do
    save_hug(socket, socket.assigns.action, hug_params)
  end

  defp save_hug(socket, :edit, hug_params) do
    case Hugs.update_hug(socket.assigns.hug, hug_params) do
      {:ok, _hug} ->
        {
          :noreply,
          socket
          |> put_flash(:info, "Hug updated successfully")
          |> push_redirect(to: socket.assigns.return_to)
        }

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_hug(socket, :new, hug_params) do
    case Hugs.create_hug(socket.assigns.current_user, hug_params) do
      {:ok, _hug} ->
        {
          :noreply,
          socket
          |> put_flash(:info, "Hug created successfully")
          |> push_redirect(to: socket.assigns.return_to)
        }

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/catex_web/live/hug_live/index.ex
defmodule CatexWeb.HugLive.Index do
  @moduledoc false

  use CatexWeb, :live_view

  alias Catex.Hugs
  alias Catex.Hugs.Hug
  alias Catex.Users

  @impl true
  def mount(_params, %{"user_id" => user_id} = _session, socket) do
    {
      :ok,
      socket
      |> assign_new(:current_user, fn -> Users.get_user!(user_id) end)
      |> assign(:hugs, list_hugs(user_id))
    }
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Hug")
    |> assign(:hug, Hugs.get_hug!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Hug")
    |> assign(:hug, %Hug{participants: []})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Hugs")
    |> assign(:hugs, list_hugs(socket.assigns.current_user.id))
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    hug = Hugs.get_hug!(id)
    {:ok, _} = Hugs.delete_hug(hug)

    {:noreply, assign(socket, :hugs, list_hugs(socket.assigns.current_user.id))}
  end

  defp list_hugs(user_id) do
    Hugs.list_hugs_from_user(user_id)
  end
end

lib/catex_web/live/hug_live/show.ex
defmodule CatexWeb.HugLive.Show do
  @moduledoc false

  use CatexWeb, :live_view

  alias Catex.Hugs

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:hug, Hugs.get_hug!(id))}
  end

  defp page_title(:show), do: "Show Hug"
  defp page_title(:edit), do: "Edit Hug"
end

lib/catex_web/live/live_helpers.ex
defmodule CatexWeb.LiveHelpers do
  @moduledoc false

  import Phoenix.LiveView
  import Phoenix.LiveView.Helpers

  alias Phoenix.LiveView.JS

  @doc """
  Renders a live component inside a modal.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <.modal return_to={Routes.hug_index_path(@socket, :index)}>
        <.live_component
          module={CatexWeb.HugLive.FormComponent}
          id={@hug.id || :new}
          title={@page_title}
          action={@live_action}
          return_to={Routes.hug_index_path(@socket, :index)}
          hug: @hug
        />
      </.modal>
  """
  def modal(assigns) do
    assigns = assign_new(assigns, :return_to, fn -> nil end)

    ~H"""
    <div id="modal" class="phx-modal fade-in" phx-remove={hide_modal()}>
      <div
        id="modal-content"
        class="phx-modal-content fade-in-scale"
        phx-click-away={JS.dispatch("click", to: "#close")}
        phx-window-keydown={JS.dispatch("click", to: "#close")}
        phx-key="escape"
      >
        <%= if @return_to do %>
          <%= live_patch "✖",
            to: @return_to,
            id: "close",
            class: "phx-modal-close",
            phx_click: hide_modal()
          %>
        <% else %>
          <a id="close" href="#" class="phx-modal-close" phx-click={hide_modal()}>✖</a>
        <% end %>

        <%= render_slot(@inner_block) %>
      </div>
    </div>
    """
  end

  defp hide_modal(js \\ %JS{}) do
    js
    |> JS.hide(to: "#modal", transition: "fade-out")
    |> JS.hide(to: "#modal-content", transition: "fade-out-scale")
  end
end

lib/catex_web/live/hug_live/form_component.html.heex
<div>
  <h3><%= @title %></h3>

  <.form
    let={f}
    for={@changeset}
    id="hug-form"
    phx-target={@myself}
    phx-submit="save"
    phx-change="validate">

    <%= inputs_for f, :participants, fn participant_form -> %>
      <%= text_input participant_form, :temp_id, hidden: true %>
      <div class="columns">
        <div class="column is-4">
          <div class="field">
            <%= label participant_form, :user_id, class: "label" %>
            <%= if @action == :edit do %>
              <p><%= participant_form.data.user.name %></p>
            <% else %>
              <div class="control">
                <div class="select">
                  <%= select(participant_form, :user_id, @users) %>
                </div>
              </div>
            <% end %>
            <%= error_tag participant_form, :user_id %>
          </div>
        </div>

        <%= if @action == :edit do %>
        <div class="column is-6">
          <%= label participant_form, :status, class: "label" %>
          <p><%= String.replace(Atom.to_string(participant_form.data.status), "_", " ") %></p>
          <%= if participant_form.data.user.id == @current_user.id do %>
            <%= if ! (Map.get(@status_opts, participant_form.data.status) |> Enum.empty?()) do %>
              <div class="select">
                <%= select(participant_form, :status, Map.get(@status_opts, participant_form.data.status)) %>
              </div>
              <%= error_tag participant_form, :status %>
            <% end %>
          <% end %>
        </div>
        <% end %>

        <!-- TODO Add this back
        <div class="column">
          <button class="button is-small is-danger is-inverted">
           <span class="icon is-small is-left">
             <i class="fas fa-trash-can"></i>
           </span>
          </button>
        </div>
        -->
      </div>
    <% end %>

    <div class="field">
      <div class="control">
        <a href="#" phx-target={@myself} phx-click="add_participant" class="button is-small">Add a participant</a>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= submit "Save", phx_disable_with: "Saving...", class: "button" %>
      </div>
    </div>
  </.form>
</div>

lib/catex_web/live/hug_live/index.html.heex
<h1>Le Hugs</h1>

<%= if @live_action in [:new, :edit] do %>
  <.modal return_to={Routes.hug_index_path(@socket, :index)}>
    <.live_component
      module={CatexWeb.HugLive.FormComponent}
      id={@hug.id || :new}
      title={@page_title}
      action={@live_action}
      hug={@hug}
      return_to={Routes.hug_index_path(@socket, :index)}
      current_user={@current_user}
    />
  </.modal>
<% end %>

<div class="section">
  <div class="columns">
    <div class="column is-6">
      <div class="card">
        <header class="card-header">
          <p class="card-header-title">
            Hugs you initiated
          </p>
        </header>
        <div class="card-content">
          <div class="content">
            <table class="table">
              <thead>
              <tr>
                <th>ID</th>
                <th><span>Participants</span></th>
                <th><span>Actions</span></th>
              </tr>
              </thead>
              <tbody>
              <%= for hug <- (@hugs |> Enum.filter(&(&1.initiator_id == @current_user.id))) do %>
                <tr id={"hug-#{hug.id}"}>
                  <td><%= hug.id %></td>
                  <td>
                    <%= for p <- hug.participants do %>
                    <span><%= "#{String.pad_trailing(p.user.name, 10)} - #{p.status |> Atom.to_string |> String.replace("_", " ") }" %></span>
                    <br/>
                    <% end %>
                  </td>
                  <td>
                    <!--<span><%= live_redirect "Show", to: Routes.hug_show_path(@socket, :show, hug) %></span>-->
                    <div class="field has-addons">
                      <%= if (hug.participants |> Enum.filter(&(&1.user.id == @current_user.id)) |> hd).status not in [:hug_confirmed, :hug_denied] do %>
                      <p class="control">
                        <%= live_patch class: "button is-link is-small is-rounded is-outlined",
                                   to: Routes.hug_index_path(@socket, :edit, hug) do %>
                        <span class="icon is-small">
                              <i class="fas fa-pen-to-square"></i>
                            </span>
                        <span>Edit</span>
                        <% end %>
                      </p>
                      <% end %>
                      <p class="control">
                        <%= link class: "button is-danger is-small is-rounded is-outlined",
                                 to: "#", phx_click: "delete", phx_value_id: hug.id, data: [confirm: "Are you sure?"] do %>
                        <span class="icon is-small">
                            <i class="fas fa-trash-can"></i>
                          </span>
                        <span>Delete</span>
                        <% end %>
                      </p>
                    </div>

                  </td>
                </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
        <footer class="card-footer">
          <%= live_patch "New Hug", to: Routes.hug_index_path(@socket, :new), class: "card-footer-item" %>
        </footer>
      </div>
    </div>
    <div class="column is-6">
      <div class="card">
        <header class="card-header">
          <p class="card-header-title">
            Hugs you got offered
          </p>
        </header>
        <div class="card-content">
          <div class="content">
            <table class="table">
              <thead>
              <tr>
                <th>ID</th>
                <th><span>Participants</span></th>
                <th><span>Actions</span></th>
              </tr>
              </thead>
              <tbody id="hugs">
              <%= for hug <- (@hugs |> Enum.filter(&(&1.initiator_id != @current_user.id)))  do %>
              <tr id={"hug-#{hug.id}"}>
                <td><%= hug.id %></td>
                <td>
                  <%= for p <- hug.participants do %>
                  <span><%= "#{String.pad_trailing(p.user.name, 10)} - #{p.status |> Atom.to_string |> String.replace("_", " ") }" %></span>
                  <br/>
                  <% end %>
                </td>
                <td>
                  <!--<span><%= live_redirect "Show", to: Routes.hug_show_path(@socket, :show, hug) %></span>-->
                  <div class="field has-addons">
                    <%= if (hug.participants |> Enum.filter(&(&1.user.id == @current_user.id)) |> hd).status not in [:hug_confirmed, :hug_denied] do %>
                    <p class="control">
                      <%= live_patch class: "button is-link is-small is-rounded is-outlined",
                                 to: Routes.hug_index_path(@socket, :edit, hug) do %>
                      <span class="icon is-small">
                            <i class="fas fa-pen-to-square"></i>
                          </span>
                      <span>Edit</span>
                      <% end %>
                    </p>
                    <% end %>
                  </div>

                </td>
              </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<br/>

lib/catex_web/live/hug_live/show.html.heex
<h1>Show Hug</h1>

<%= if @live_action in [:edit] do %>
  <.modal return_to={Routes.hug_show_path(@socket, :show, @hug)}>
    <.live_component
      module={CatexWeb.HugLive.FormComponent}
      id={@hug.id}
      title={@page_title}
      action={@live_action}
      hug={@hug}
      return_to={Routes.hug_show_path(@socket, :show, @hug)}
    />
  </.modal>
<% end %>

<ul>
  <li><%= @hug.id %></li>
  <li><%= @hug.participants |> Enum.map(&("#{&1.user.name} (#{&1.status})")) |> Enum.join("; ") %></li>
</ul>

<span><%= live_patch "Edit", to: Routes.hug_show_path(@socket, :edit, @hug), class: "button" %></span> |
<span><%= live_redirect "Back", to: Routes.hug_index_path(@socket, :index) %></span>