lib/catex_web/router.ex
defmodule CatexWeb.Router do
  @moduledoc false

  use CatexWeb, :router

  import CatexWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {CatexWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Catex.Authenticator
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through [:browser]

      live_dashboard "/dashboard",
        metrics: CatexWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

#  scope "/", CatexWeb do
#    pipe_through [:browser, :redirect_if_user_is_authenticated]
#
#    get "/users/register", UserRegistrationController, :new
#    post "/users/register", UserRegistrationController, :create
#    get "/users/log_in", UserSessionController, :new
#    post "/users/log_in", UserSessionController, :create
#    get "/users/reset_password", UserResetPasswordController, :new
#    post "/users/reset_password", UserResetPasswordController, :create
#    get "/users/reset_password/:token", UserResetPasswordController, :edit
#    put "/users/reset_password/:token", UserResetPasswordController, :update
#  end

  scope "/", CatexWeb do
    pipe_through [:browser, :require_authenticated_user]

    live "/hugs", HugLive.Index, :index
    live "/hugs/new", HugLive.Index, :new
    live "/hugs/:id/edit", HugLive.Index, :edit

    live "/hugs/:id", HugLive.Show, :show
    live "/hugs/:id/show/edit", HugLive.Show, :edit
  end

  scope "/admin", CatexWeb.Admin, as: :admin do
    pipe_through [:browser, :require_authenticated_user, :require_admin_user]

    resources "/users", UserController
    resources "/hugs", HugController
  end

  scope "/", CatexWeb do
    pipe_through [:browser]

    get "/", PageController, :index

    # Below 2 routers under redirect?
    get "/auth/login", AuthController, :login
    get "/auth/callback", AuthController, :callback

#    delete "/users/log_out", UserSessionController, :delete
    get "/auth/logout", AuthController, :logout
  end

  # Other scopes may use custom stacks.
  scope "/api", CatexWeb do
    pipe_through :api

    get "/hugs", HugController, :index
  end
end

lib/catex_web/views/layout_view.ex
defmodule CatexWeb.LayoutView do
  @moduledoc false

  use CatexWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/catex_web/templates/layout/_user_menu.html.heex
<ul>
  <%= if @current_user != nil and @current_user.admin do %>

    <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
     <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
    <% end %>

    <li><%= link "Admin", to: Routes.admin_user_path(@conn, :index) %></li>

    <br/>
  <% end %>

  <%= if @current_user do %>
    <li><%= link "Manage hugs", to: Routes.hug_index_path(@conn, :index) %></li>
    <li><%= link "Logout", to: Routes.auth_path(@conn, :logout) %></li>
  <% else %>
    <li><%= link "Login", to: Routes.auth_path(@conn, :login) %></li>
  <% end %>
</ul>

lib/catex_web/templates/layout/app.html.heex
<main class="container-full">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/catex_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/catex_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no"/>

    <meta name="csrf-token" content={csrf_token_value()}>
    <%= live_title_tag assigns[:page_title] || "Catex", suffix: " · Phoenix Framework" %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav>
          <%= render "_user_menu.html", assigns %>
        </nav>
        <span>
          <%= if @current_user != nil do %>
            Welcome <%= @current_user.name %>
          <% end %>
        </span>
        <a href="/" class="phx-logo">
          <img src={Routes.static_path(@conn, "/images/cat_hollow_purple.png")} alt="Cat Logo"/>
        </a>
      </section>
    </header>
    <%= @inner_content %>
 </body>
</html>

lib/catex_web/templates/layout/torch.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <title>Admin</title>
    <!-- Uncomment to just use the bare bones torch styles rather than the theme -->
    <!--<link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/torch/base.css")}>-->
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/torch/theme.css")}>
  </head>

  <body class={Torch.PageView.body_classes(@conn)}>
    <header>
      <section id="torch-account-info">
        <div class="torch-container">
          <a href="/">user@example.com</a>
          <a href="/">Logout</a>
        </div>
      </section>

      <section id="torch-nav">
        <div class="torch-container">
          <div class="torch-logo">
            <a href="/">
              <h3>Torch</h3>
            </a>
          </div>
          <nav class="torch-nav">
            <%= link "Users", to: Routes.admin_user_path(@conn, :index) %>
            <%= link "Hugs", to: Routes.admin_hug_path(@conn, :index) %>
            <!-- nav links here -->
          </nav>
        </div>
      </section>
    </header>

    <%= Torch.FlashView.render("_flash_messages.html", assigns) %>
    <%= @inner_content %>
    <script defer src={Routes.static_path(@conn, "/torch/torch.js")}></script>
  </body>
</html>